version: '3'

services:
  react-app:	
    image: reactapp:latest	
    deploy:
      restart_policy:
        condition: "any"
        delay: "0"
        max_attempts: 3
        window: "30s"	
    ports: 	
      - "8080"	
    networks:	
      - bridge	
    labels:	
      - "traefik.http.routers.reactboilerplate.rule=Host(`reactapp.dockerbox.local`)"
      - "traefik.docker.network=bridge"
      - "traefik.http.services.reactboilerplate.loadbalancer.server.port=8080"

networks:
  bridge:
    external: true
